name = "IbPDemo"
uuid = "eb60036e-0944-45ec-a036-952f0993839f"
authors = ["Shashank Swaminathan"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
